name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Debug Secrets
      run: |
        echo "DOCKER_USERNAME length: ${#DOCKER_USERNAME}"
        echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build and Tag Docker Image
      run: |
        docker build -t $DOCKER_USERNAME/williamcare:latest .

    - name: Push Docker Image
      run: |
        docker tag $DOCKER_USERNAME/my-app:latest $DOCKER_USERNAME/williamcare:latest
        docker push $DOCKER_USERNAME/williamcare:latest
